baseURL: '/'
languageCode: en-us
title: Axa Hugo Docs
relativeURLs: true

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6
  
params:
  env: "azure"
  version: "v1.0"
 
